name: C++ CI

on:
  push:
    branches: [ master ]
  pull-request:
    branches: [ master ]
    
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: sudo apt install -y build-essentials
          - name: Compile C++ 2017
            run: g++ main.cpp -std=c++17 -o Bugtastic
            
